baseURL = "http://oliverschmid.space/"
languageCode = "en-us"
title = "Oliver Schmid"
theme = "aerial"

[params]
  Name = "Oliver Schmid"
  About = "Software Developer  •  Thinker  •  Trying to Live Forever"
