baseURL = "https://oliverschmid.space/"
enableRobotsTXT = true
paginate = 5
theme = "website-theme"
title = "Oliver Schmid"

[params]
  description = "My personal blog"

[sitemap]
  changeFreq = "weekly"
  priority = "0.5"