baseURL = "https://oliverschmid.space/"
languageCode = "en-us"
title = "Oliver Schmid"
theme = "aerial"

[params]
  name = "Oliver Schmid"
  about = "Software Developer  •  Thinker  •  Trying to Live Forever"
  bg_scroll = "disable"
  favicon = "favicon-adjust.ico"
  copyright = "Oliver Schmid"
