baseURL = "https://oliverschmid.space/"
enableRobotsTXT = true
paginate = 5
rssLimit = 20
title = "Oliver Schmid"

[params]
  description = "Personal Blog"
  defaultLicense = "cc-by-4.0"
  appleTouchIcon = "/favicon-touch.png"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[sitemap]
  changeFreq = "weekly"
  priority = "0.5"