[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.92.2"
  RUBY_VERSION = "3.0"

[dev]
  framework = "hugo"
  port = 8888
  functionsPort = 9999

[functions]
  node_bundler = "esbuild"
  included_files = ["!*.test.js"]