[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.58.3"
  RUBY_VERSION = "2.6.2"

[dev]
  framework = "hugo"
  port = 8888
  functionsPort = 9999

[functions]
  node_bundler = "esbuild"
