#!/bin/sh

git log origin..HEAD

# Read user input, assign stdin to keyboard
exec < /dev/tty

D="\e[37m" # default
H="\e[39m" # highlight
S="\e[33m" #section

CL=$(cat <<-EOM

${S}Checklist${D}

1 Rebase, build, and unit test
2 App still ${H}starts${D}?
3 ${H}Sanity$D test change
4 Functionality ${H}around$D your change still works?
5 Commit includes ${H}all/only$D necessary files?
6 Review ${H}diffs$D for TODOs and refactors?
7 Is each change in a commit ${H}related${D}?
8 ${H}Clearest$D possible commit messages?
9 Update ${H}docs${D}?

${S}Continue with push? (Y/n):$D 
EOM
)
echo "$CL"

while read yn; do
  case $yn in
    Y|y|"") break;;
    N|n) exit 1;;
    *) echo "Please answer y (yes) or n (no):" && continue;
  esac
done

exec <&-
